app/src/main/frontend/src/App.js, app/src/main/frontend/src/Login.js, app/src/main/java/bitcamp/project/controller/AuthController.java, app/src/main/java/bitcamp/project/dao/UserDao.java, app/src/main/java/bitcamp/project/service/UserService.java, app/src/main/java/bitcamp/project/service/impl/UserServiceImpl.java, app/src/main/resources/mapper/UserMapper.xml
=> user interface

.idea/gradle.xml, app/src/main/java/bitcamp/project/controller/FaqController.java, app/src/main/java/bitcamp/project/controller/UserController.java, app/src/main/java/bitcamp/project/dao/FaqDao.java, app/src/main/java/bitcamp/project/service/FaqService.java, app/src/main/java/bitcamp/project/service/impl/FaqServiceImpl.java, app/src/main/java/bitcamp/project/vo/Faq.java, app/src/main/resources/bitcamp/project/dao/FaqDao.xml, docs/ddl.txt
=> feat. faq 관련 기능 추가

app/src/main/resources/bitcamp/project/dao/UserDao.xml
=> 토큰에 데이터 추가

.idea/modules.xml, .idea/modules/app/bitcamp-final.app.main.iml, app/src/main/java/bitcamp/project/controller/UserController.java, app/src/main/java/bitcamp/project/service/UserService.java, app/src/main/java/bitcamp/project/service/impl/UserServiceImpl.java
=> token decode

app/src/main/frontend/src/assets/styles/css/SignUp.module.css, app/src/main/frontend/src/assets/styles/css/_variables.css, app/src/main/frontend/src/routes/Login.js, app/src/main/frontend/src/routes/SignUp.js, app/src/main/java/bitcamp/project/controller/AuthController.java, app/src/main/java/bitcamp/project/dto/EmailDTO.java
=> 회원가입 이메일 인증에러수정

app/src/main/frontend/src/routes/MyPage.js, app/src/main/java/bitcamp/project/controller/UserController.java, app/src/main/java/bitcamp/project/interceptor/AuthInterceptor.java
=> 유저 찾기 토큰사용으로 수정

app/src/main/frontend/package-lock.json, app/src/main/frontend/src/App.js, app/src/main/java/bitcamp/project/security/JwtTokenProvider.java
로그인시 1시간이 지나면 알림후 다시 로그인 화면으로 가기
=> 로그인시 1시간이 지나면 알림후 다시 로그인 화면으로 가기

app/src/main/frontend/src/assets/styles/css/SignUp.module.css, app/src/main/frontend/src/assets/styles/css/_variables.css, app/src/main/frontend/src/routes/SignUp.js
=> 이메일 중복 검사추가

app/src/main/frontend/src/components/Header.js, app/src/main/frontend/src/components/ReauthenticateModal.js, app/src/main/frontend/src/routes/MyPage.js, app/src/main/java/bitcamp/project/controller/UserController.java, app/src/main/java/bitcamp/project/security/JwtTokenProvider.java, app/src/main/java/bitcamp/project/service/UserService.java, app/src/main/java/bitcamp/project/service/impl/UserServiceImpl.java, app/src/main/resources/bitcamp/project/dao/UserDao.xml
=> edit user(end)

app/src/main/java/bitcamp/project/controller/UserController.java, app/src/main/java/bitcamp/project/service/StoryService.java, app/src/main/java/bitcamp/project/service/impl/StoryServiceImpl.java, app/src/main/java/bitcamp/project/service/impl/UserServiceImpl.java
=> 회원 탈퇴, 유저정보수정 UI수정

app/src/main/java/bitcamp/project/controller/UserController.java
=> 어드민 회원삭제 추가

app/src/main/java/bitcamp/project/controller/StoryController.java, app/src/main/java/bitcamp/project/dao/StoryDao.java, app/src/main/java/bitcamp/project/service/StoryService.java, app/src/main/java/bitcamp/project/service/impl/StoryServiceImpl.java, app/src/main/resources/bitcamp/project/dao/StoryDao.xml
=> 스크롤 무한 로딩(공유 스토리)

app/src/main/java/bitcamp/project/controller/StoryController.java, app/src/main/java/bitcamp/project/dao/StoryDao.java, app/src/main/java/bitcamp/project/service/impl/StoryServiceImpl.java, app/src/main/resources/bitcamp/project/dao/StoryDao.xml
=> 내 스토리 무한스크롤

app/src/main/java/bitcamp/project/controller/StoryController.java, app/src/main/java/bitcamp/project/dao/StoryDao.java, app/src/main/java/bitcamp/project/service/impl/StoryServiceImpl.java, app/src/main/resources/bitcamp/project/dao/StoryDao.xml
=> 타이머 및 무한스크롤 오류 수정

app/src/main/java/bitcamp/project/controller/StoryController.java, app/src/main/java/bitcamp/project/dao/StoryDao.java, app/src/main/java/bitcamp/project/service/impl/StoryServiceImpl.java, app/src/main/resources/bitcamp/project/dao/StoryDao.xml
=> 스크롤 오류 수정, 과거 정렬 수정

app/src/main/java/bitcamp/project/service/impl/MailServiceImpl.java
=> 오류수정 및 아이디 찾기 기능 개선

app/src/main/java/bitcamp/project/controller/StoryController.java, app/src/main/java/bitcamp/project/dao/StoryDao.java, app/src/main/java/bitcamp/project/service/StoryService.java, app/src/main/java/bitcamp/project/service/impl/StoryServiceImpl.java, app/src/main/java/bitcamp/project/service/impl/UserServiceImpl.java, app/src/main/resources/bitcamp/project/dao/StoryDao.xml
=> 어드민 스토리 삭제

app/src/main/java/bitcamp/project/security/OAuthAuthenticationSuccessHandler.java
소셜로그인 시 USER 객체 없음 == 회원이 아님일 때
회원가입 페이지 링크로 리다이렉션
소셜로그인에서 끌어온 정보로 항목 미리 채움
인증번호 삭제
=> feat: 소셜로그인 회원가입 추가

app/src/main/java/bitcamp/project/WebConfig.java
=> Lee tae jung

app/src/main/java/bitcamp/project/controller/AuthController.java
=> add default
